import { useEffect } from 'react';
import { useLocation } from 'react-router-dom';
import { ORG } from '../config/organization.js';

// Default social-share image (1200x630, generated by scripts/generate-og-image.js).
// Pages may override with their own `image` (absolute URL) when variants exist.
const DEFAULT_OG_IMAGE = `${ORG.url}/og-default.png`;

export const useSEO = ({ title, description, keywords, schema, abstract, image }) => {
  const { pathname } = useLocation();

  useEffect(() => {
    const setMeta = (name, content, isProperty = false) => {
      if (!content) return;
      const attr = isProperty ? 'property' : 'name';
      let tag = document.querySelector(`meta[${attr}="${name}"]`);
      if (!tag) {
        tag = document.createElement('meta');
        tag.setAttribute(attr, name);
        document.head.appendChild(tag);
      }
      tag.content = content;
    };

    if (title) {
      document.title = title;
      setMeta('og:title', title, true);
      setMeta('twitter:title', title);
    }

    if (description) {
      setMeta('description', description);
      setMeta('og:description', description, true);
      setMeta('twitter:description', description);
    }
    if (keywords) setMeta('keywords', keywords);
    if (abstract) setMeta('abstract', abstract);

    // Open Graph / Twitter card (og:url mirrors the canonical URL exactly)
    const clean = pathname.replace(/\/+$/, '') || '/';
    setMeta('og:url', clean === '/' ? `${ORG.url}/` : `${ORG.url}${clean}`, true);
    setMeta('og:type', 'website', true);
    setMeta('og:site_name', ORG.name, true);
    setMeta('og:locale', 'en_IN', true);

    const ogImage = image || DEFAULT_OG_IMAGE;
    setMeta('og:image', ogImage, true);
    setMeta('og:image:width', '1200', true);
    setMeta('og:image:height', '630', true);
    setMeta('og:image:alt', `${ORG.name} — digital growth agency, Hyderabad`, true);
    setMeta('twitter:card', 'summary_large_image');
    setMeta('twitter:image', ogImage);

    let script;
    if (schema) {
      script = document.querySelector('script[id="dynamic-schema"]');
      if (!script) {
        script = document.createElement('script');
        script.id = 'dynamic-schema';
        script.type = 'application/ld+json';
        document.head.appendChild(script);
      }
      script.text = typeof schema === 'string' ? schema : JSON.stringify(schema);
    }

    return () => {
      // Remove schema on unmount to prevent lingering on other pages
      if (script) script.remove();
    };
  }, [title, description, keywords, schema, abstract, image, pathname]);
};
