import React from 'react';
import { useSEO } from '../hooks/useSEO';
import { Reveal, SecNum, waLink } from '../components/ui/primitives';

const mono = (extra = {}) => ({ fontFamily: "'IBM Plex Mono',monospace", ...extra });

const FARHAN_PILLARS = [
  {
    num: '01',
    title: 'Direct-Response Creative Systems',
    desc: 'Engineering high-performing video ads, scroll-stopping hooks, and graphic ad variations built to convert cold traffic into customers.',
  },
  {
    num: '02',
    title: 'Brand Identity & Visual Architecture',
    desc: 'Crafting premium, memorable brand identities with custom typography, color palettes, motion guidelines, and packaging designs.',
  },
  {
    num: '03',
    title: 'Conversion UI/UX Design',
    desc: 'Designing intuitive web and mobile app user interfaces that eliminate user friction, increase time-on-site, and maximize checkout completions.',
  },
  {
    num: '04',
    title: 'Content & Motion Production',
    desc: 'Directing short-form reels, product photography, pitch decks, and promotional video assets tailored for multi-platform distribution.',
  },
];

const FARHAN_METRICS = [
  { value: '500M+', label: 'Views Generated by Creative' },
  { value: '100+', label: 'Brand Identities Crafted' },
  { value: '3x', label: 'Higher Click-Through Rates' },
  { value: '0', label: 'Generic Templates Used' },
];

const FARHAN_LAWS = [
  { title: 'Design is Direction', desc: 'Visuals must guide the user\'s eyes toward action, not just look pretty in a portfolio.' },
  { title: 'Hook in 3 Seconds', desc: 'In digital feeds, the first 3 seconds decide if a customer pays attention or scrolls past.' },
  { title: 'Consistency Builds Trust', desc: 'Unified visual identity across web, social, packaging, and ads builds enterprise credibility.' },
  { title: 'Clarity Over Clutter', desc: 'Clean, bold design hierarchy converts better than crowded, noisy visuals.' },
];

const FarhanProfilePage = () => {
  useSEO({
    title: 'Mohammed Farhan Azeez | Creative Director at Creativals',
    description: 'Meet Mohammed Farhan Azeez, Creative Director at Creativals. Crafting direct-response video ad creative, brand identity, and UI/UX design systems.',
    keywords: 'Mohammed Farhan Azeez, Farhan Azeez, Creative Director Creativals, brand identity designer hyderabad, direct response video ads, UI UX designer',
    schema: {
      '@context': 'https://schema.org',
      '@type': 'Person',
      name: 'Mohammed Farhan Azeez',
      alternateName: 'Farhan Azeez',
      jobTitle: 'Creative Director',
      worksFor: {
        '@type': 'Organization',
        name: 'Creativals',
        url: 'https://creativals.com',
      },
      url: 'https://creativals.com/mohammed-farhan-azeez',
      image: 'https://creativals.com/farhan.webp',
      sameAs: [
        'https://in.linkedin.com/in/mohammed-farhan-azeez',
      ],
      description: 'Creative Director at Creativals. Directing visual identity, direct-response ad creative, motion graphics, and UI/UX design systems.',
    },
  });

  return (
    <div>
      {/* ── HERO SECTION ── */}
      <section style={{ background: '#4F46E5', color: '#F4F2EC' }}>
        <div className="cx-wrap" style={{ paddingTop: 96, paddingBottom: 90 }}>
          <Reveal>
            <div style={mono({ fontSize: 12, letterSpacing: '.16em', textTransform: 'uppercase', display: 'flex', alignItems: 'center', gap: 12, marginBottom: 30 })}>
              <span className="cx-dot" />
              Inside Creativals · Executive Profile · @farhan
            </div>
          </Reveal>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 48, alignItems: 'center' }}>
            <div>
              <Reveal delay={60}>
                <h1 className="cx-display cx-h1" style={{ marginBottom: 16 }}>
                  Mohammed Farhan Azeez
                </h1>
              </Reveal>
              <Reveal delay={100}>
                <div style={{ fontSize: 'clamp(18px, 2.2vw, 24px)', fontWeight: 700, color: '#FFD84D', marginBottom: 24, fontStyle: 'italic' }}>
                  Creative Director · Brand & UI/UX Strategist
                </div>
              </Reveal>
              <Reveal delay={140}>
                <p style={{ margin: '0 0 32px', fontSize: 18, lineHeight: 1.6, color: 'rgba(244,242,236,.88)', maxWidth: 540 }}>
                  Directing creative strategy, visual identity, and high-conversion UI/UX at Creativals. Farhan turns brand storytelling into measurable direct-response performance.
                </p>
              </Reveal>
              <Reveal delay={180}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 14, flexWrap: 'wrap' }}>
                  <a
                    href="https://in.linkedin.com/in/mohammed-farhan-azeez"
                    target="_blank"
                    rel="noreferrer"
                    className="cx-btn cx-btn-lg cx-btn-yellow"
                    style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}
                  >
                    LinkedIn Profile ↗
                  </a>
                  <a
                    href={waLink('Hi Farhan! I read your profile on Creativals and want to consult on branding and video ad creatives.')}
                    target="_blank"
                    rel="noreferrer"
                    className="cx-btn cx-btn-lg"
                    style={{ background: 'rgba(244,242,236,.12)', color: '#F4F2EC', border: '1px solid rgba(244,242,236,.25)' }}
                  >
                    Creative Consult with Farhan →
                  </a>
                </div>
              </Reveal>
            </div>

            {/* Profile Avatar Card */}
            <Reveal delay={120}>
              <div
                className="cx-card tilt-r"
                style={{
                  padding: 24,
                  background: '#17151A',
                  color: '#F4F2EC',
                  border: '3px solid #17151A',
                  borderRadius: 24,
                  boxShadow: '8px 8px 0px rgba(255,216,77,.85)',
                  maxWidth: 380,
                  margin: '0 auto',
                }}
              >
                <div style={{ width: '100%', aspectRatio: '1/1', borderRadius: 16, overflow: 'hidden', border: '2px solid rgba(244,242,236,.2)', marginBottom: 20 }}>
                  <img
                    src="/farhan.webp"
                    alt="Mohammed Farhan Azeez"
                    width="380"
                    height="380"
                    style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }}
                  />
                </div>
                <div style={mono({ fontSize: 11, letterSpacing: '.14em', textTransform: 'uppercase', color: '#FFD84D', marginBottom: 8 })}>
                  CREATIVE PHILOSOPHY
                </div>
                <p style={{ margin: 0, fontSize: 17, fontWeight: 700, lineHeight: 1.4, fontStyle: 'italic' }}>
                  "Design is not decoration. It's direction."
                </p>
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 18 }}>
                  <span className="cx-tag cx-tag-indigo">Branding</span>
                  <span className="cx-tag cx-tag-indigo">Design</span>
                  <span className="cx-tag cx-tag-indigo">Video</span>
                  <span className="cx-tag cx-tag-indigo">Visual Identity</span>
                </div>
              </div>
            </Reveal>
          </div>
        </div>
      </section>

      {/* ── SECTION 1 — CREATIVE APPROACH ── */}
      <section style={{ background: '#F4F2EC', color: '#17151A' }}>
        <div className="cx-wrap cx-section">
          <Reveal><SecNum n="01" label="The Creative Vision" /></Reveal>
          <Reveal delay={60}>
            <h2 className="cx-display cx-h2" style={{ marginBottom: 28 }}>
              Performance design.<br />
              <span style={{ color: '#4F46E5', fontStyle: 'italic' }}>Built for conversion.</span>
            </h2>
          </Reveal>

          <div className="cx-grid2" style={{ alignItems: 'start', marginBottom: 56 }}>
            <Reveal delay={120}>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
                <p className="cx-lead" style={{ fontSize: 19, fontWeight: 600, color: '#17151A' }}>
                  Mohammed Farhan Azeez directs visual strategy, brand identity design, and video production for Creativals and its global portfolio of clients.
                </p>
                <p className="cx-lead">
                  Farhan believes design should never exist in a vacuum. Every graphic, video hook, logo asset, and user interface is engineered to guide the customer's attention, communicate trust instantly, and drive action.
                </p>
                <p className="cx-lead">
                  From direct-response reel ads that cut through noisy social media feeds to enterprise branding systems and mobile app UI/UX, Farhan ensures visual assets deliver high return on investment.
                </p>
              </div>
            </Reveal>

            <Reveal delay={180}>
              <div className="cx-card tilt-l" style={{ boxSizing: 'border-box', padding: 32 }}>
                <div style={mono({ fontSize: 11, fontWeight: 600, letterSpacing: '.14em', textTransform: 'uppercase', color: '#4F46E5', marginBottom: 18 })}>
                  Creative Expertise
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
                  <div style={{ display: 'flex', gap: 12, fontSize: 15, color: 'rgba(23,21,26,.8)' }}>
                    <span style={{ color: '#3DDC84', fontWeight: 900 }}>✓</span>
                    <span><strong>Direct-Response Video Ads:</strong> High-hook short-form videos engineered for TikTok, Reels, and YouTube Shorts.</span>
                  </div>
                  <div style={{ display: 'flex', gap: 12, fontSize: 15, color: 'rgba(23,21,26,.8)' }}>
                    <span style={{ color: '#3DDC84', fontWeight: 900 }}>✓</span>
                    <span><strong>Full Brand Identity Systems:</strong> Logo design, typography scale, visual guidelines, and brand books.</span>
                  </div>
                  <div style={{ display: 'flex', gap: 12, fontSize: 15, color: 'rgba(23,21,26,.8)' }}>
                    <span style={{ color: '#3DDC84', fontWeight: 900 }}>✓</span>
                    <span><strong>Conversion UI/UX Architecture:</strong> Designing intuitive, beautiful web and app interfaces.</span>
                  </div>
                  <div style={{ display: 'flex', gap: 12, fontSize: 15, color: 'rgba(23,21,26,.8)' }}>
                    <span style={{ color: '#3DDC84', fontWeight: 900 }}>✓</span>
                    <span><strong>Pitch Decks & Print Collateral:</strong> Investor decks, packaging design, and high-impact physical assets.</span>
                  </div>
                </div>
              </div>
            </Reveal>
          </div>
        </div>
      </section>

      {/* ── SECTION 2 — CREATIVE PILLARS (YELLOW) ── */}
      <section style={{ background: '#FFD84D', color: '#17151A', borderTop: '4px solid #17151A', borderBottom: '4px solid #17151A' }}>
        <div className="cx-wrap cx-section">
          <Reveal><SecNum n="02" label="Creative Pillars" yellow /></Reveal>
          <Reveal delay={60}>
            <h2 className="cx-display cx-h2" style={{ marginBottom: 40 }}>
              Design principles Farhan uses to<br />
              <span style={{ color: '#4F46E5', fontStyle: 'italic' }}>elevate brand presence.</span>
            </h2>
          </Reveal>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: 24 }}>
            {FARHAN_PILLARS.map((p, idx) => (
              <Reveal key={p.num} delay={idx * 80}>
                <div className="cx-card" style={{ height: '100%', boxSizing: 'border-box', padding: 28 }}>
                  <div style={{ fontWeight: 900, fontSize: 32, color: '#4F46E5', marginBottom: 12 }}>{p.num}</div>
                  <div style={{ fontWeight: 800, fontSize: 20, marginBottom: 10 }}>{p.title}</div>
                  <p style={{ margin: 0, fontSize: 14.5, lineHeight: 1.6, color: 'rgba(23,21,26,.75)' }}>{p.desc}</p>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* ── SECTION 3 — METRICS & LAWS (DARK) ── */}
      <section style={{ background: '#17151A', color: '#F4F2EC' }}>
        <div className="cx-wrap cx-section">
          <Reveal><SecNum n="03" label="Creative Impact" yellow /></Reveal>

          {/* Metrics */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '36px 28px', margin: '40px 0 72px' }}>
            {FARHAN_METRICS.map((m, idx) => (
              <Reveal key={m.label} delay={idx * 70}>
                <div>
                  <div style={{ fontWeight: 900, fontSize: 'clamp(40px, 4.5vw, 60px)', color: '#FFD84D', lineHeight: 1 }}>
                    {m.value}
                  </div>
                  <div style={mono({ fontSize: 11, letterSpacing: '.14em', textTransform: 'uppercase', marginTop: 10, color: 'rgba(244,242,236,.6)' })}>
                    {m.label}
                  </div>
                </div>
              </Reveal>
            ))}
          </div>

          <Reveal delay={60}>
            <div style={mono({ fontSize: 12, letterSpacing: '.16em', textTransform: 'uppercase', color: 'rgba(244,242,236,.55)', marginBottom: 20 })}>
              Farhan's Design Laws
            </div>
          </Reveal>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
            {FARHAN_LAWS.map((law, idx) => (
              <Reveal key={law.title} delay={idx * 60}>
                <div
                  className="cx-sysrow"
                  style={{ gridTemplateColumns: '220px 1fr', gap: 24, padding: '20px 24px', background: 'rgba(244,242,236,.04)', border: '1px solid rgba(244,242,236,.1)', borderRadius: 16 }}
                >
                  <div style={{ fontWeight: 800, fontSize: 18, color: '#FFD84D' }}>{law.title}</div>
                  <div style={{ fontSize: 15, lineHeight: 1.55, color: 'rgba(244,242,236,.75)' }}>{law.desc}</div>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* ── SECTION 4 — CONTACT / CTA ── */}
      <section style={{ background: '#4F46E5', color: '#F4F2EC' }}>
        <div className="cx-wrap cx-section">
          <Reveal>
            <div style={mono({ fontSize: 12, letterSpacing: '.16em', textTransform: 'uppercase', display: 'flex', alignItems: 'center', gap: 12, marginBottom: 24 })}>
              <span className="cx-dot" />
              Connect with Farhan
            </div>
          </Reveal>
          <Reveal delay={60}>
            <h2 className="cx-display cx-h2-xl" style={{ marginBottom: 28 }}>
              Ready to transform your brand<br />
              <span style={{ color: '#FFD84D', fontStyle: 'italic' }}>and video ad creative?</span>
            </h2>
          </Reveal>
          <Reveal delay={120}>
            <p style={{ margin: '0 0 36px', maxWidth: 500, fontSize: 18, lineHeight: 1.55, color: 'rgba(244,242,236,.88)' }}>
              Connect with Farhan on LinkedIn or consult directly on your brand identity and creative assets.
            </p>
          </Reveal>
          <Reveal delay={180}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 16, flexWrap: 'wrap' }}>
              <a
                href="https://in.linkedin.com/in/mohammed-farhan-azeez"
                target="_blank"
                rel="noreferrer"
                className="cx-btn cx-btn-lg cx-btn-yellow"
              >
                LinkedIn Profile ↗
              </a>
              <a
                href={waLink('Hi Farhan! I read your profile on Creativals and want to consult on brand design and video creative.')}
                target="_blank"
                rel="noreferrer"
                className="cx-btn cx-btn-lg"
                style={{ background: 'rgba(244,242,236,.12)', color: '#F4F2EC', border: '1px solid rgba(244,242,236,.25)' }}
              >
                WhatsApp Creative Consult →
              </a>
            </div>
          </Reveal>
        </div>
      </section>
    </div>
  );
};

export default FarhanProfilePage;
